# To run: conda env create -f environment.yml
name: nerf
channels:
    - conda-forge
dependencies:
    - python=3.10.0
    - pip
    - cudatoolkit=11.7
    - tensorflow=2.12.0
    - numpy
    - matplotlib
    - imageio
    - imageio-ffmpeg
    - configargparse
    - ipywidgets
    - tqdm
    - pillow 
    - pprint
    - open3d
    - trimesh 
    - pyrender 
    - pymcubes 
    - pyntcloud 
    - torchvision 
    - optional 
    - random
    - typing 